Repository pupitoe/irc_toutmeva, pull requests merged in 2024-07, with the labels that each got.

#22 Parsing input
  header/Server.hpp
  header/ft_socket.hpp
  src/Server.cpp
  src/ft_socket.cpp
  src/irc_tout_me_va.cpp
Labels: enhancement

#21 Feat: add comment
  header/Server.hpp
  src/Server.cpp
  src/ft_socket.cpp
Labels: documentation

#24 Refactor select
  header/Server.hpp
  src/Server.cpp
  src/irc_tout_me_va.cpp
Labels: enhancement

#26 Fix: compilation
  header/IRCSocket.hpp
  header/Server.hpp
  header/irc_tout_me_va.hpp
  src/irc_tout_me_va.cpp
Labels: bug

#29 Fix socket
  Makefile
  header/IRCSocket.hpp
  src/IRCSocket.cpp
  src/Server.cpp
  src/ft_error.cpp
  src/irc_tout_me_va.cpp
Labels: enhancement

#28 Socket
  Makefile
  header/IRCSocket.hpp
  header/Server.hpp
  header/ft_socket.hpp
  header/irc_tout_me_va.hpp
  src/IRCSocket.cpp
  src/Server.cpp
  src/ft_error.cpp
  src/irc_tout_me_va.cpp
Labels: enhancement

#34 Feat channel
  Makefile
  header/Channel.hpp
  header/ChannelCommand.hpp
  header/Client.hpp
  header/Command.hpp
  header/ConnexionCommand.hpp
  header/IRCSocket.hpp
  header/Server.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/Client.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/Server.cpp
  src/ServerChannel.cpp
Labels: enhancement

#35 Feat channel
  Makefile
  header/Channel.hpp
  header/ChannelCommand.hpp
  header/Client.hpp
  header/Command.hpp
  header/Server.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelCommandJoinPart.cpp
  src/Client.cpp
  src/Command.cpp
  src/Server.cpp
  src/ServerChannel.cpp
  src/irc_tout_me_va.cpp
Labels: enhancement

#37 Connexion
  header/Channel.hpp
  header/Command.hpp
  header/ConnexionCommand.hpp
  header/IRCError.hpp
  src/ChannelCommand.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/IRCError.cpp
  src/Server.cpp
  src/irc_tout_me_va.cpp
Labels: enhancement
