Repository pupitoe/irc_toutmeva, pull requests merged in 2024-08, with the labels that each got.

#38 Feat: impement parsing; Fix: segfault with ':' without space
  header/Channel.hpp
  header/ChannelCommand.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelCommandJoinPart.cpp
  src/Command.cpp
Labels: bug, enhancement

#40 Feat mode
  Makefile
  header/Channel.hpp
  header/ChannelCommand.hpp
  header/Command.hpp
  header/ConnexionCommand.hpp
  header/irc_tout_me_va.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelCommandJoinPart.cpp
  src/ChannelCommandMode.cpp
  src/ChannelErrorMessages.cpp
  src/ChannelMode.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/Server.cpp
Labels: enhancement

#44 Feat connexion
  header/Client.hpp
  header/ConnexionCommand.hpp
  header/IRCError.hpp
  src/ChannelCommand.cpp
  src/ChannelCommandJoinPart.cpp
  src/ChannelCommandMode.cpp
  src/Client.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/IRCError.cpp
  src/Server.cpp
Labels: enhancement

#45 Feat protocol fix
  header/Channel.hpp
  header/ChannelCommand.hpp
  header/Client.hpp
  header/Server.hpp
  header/irc_tout_me_va.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelErrorMessages.cpp
  src/ChannelMode.cpp
  src/Client.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/IRCError.cpp
  src/Server.cpp
Labels: enhancement

#50 Fix: bad error messages for part
  src/Channel.cpp
  src/ChannelErrorMessages.cpp
Labels: bug

#54 Fix rpl msg
  header/Client.hpp
  header/Server.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelMode.cpp
  src/Client.cpp
Labels: enhancement

#57 Feat bot
  Makefile
  header/Bot.hpp
  header/BotCommand.hpp
  header/Channel.hpp
  header/ChannelCommand.hpp
  header/Client.hpp
  header/Command.hpp
  header/Morfi.hpp
  header/Server.hpp
  header/irc_tout_me_va.hpp
  src/Bot.cpp
  src/BotCommand.cpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelCommandJoinPart.cpp
  src/ChannelErrorMessages.cpp
  src/ChannelMode.cpp
  src/Client.cpp
  src/Command.cpp
  src/Morfi.cpp
  src/Server.cpp
Labels: enhancement

#60 Fix: mode dont return error message if is nick
  src/ChannelCommandMode.cpp
Labels: enhancement

#61 Feat irc error
  header/Command.hpp
  header/ConnexionCommand.hpp
  header/IRCError.hpp
  src/ChannelCommand.cpp
  src/Client.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/IRCError.cpp
  src/Server.cpp
Labels: bug, enhancement, help wanted, todo

#63 Feat refactor
  header/Channel.hpp
  header/ChannelCommand.hpp
  header/Client.hpp
  header/Command.hpp
  header/ConnexionCommand.hpp
  header/IRCError.hpp
  header/Server.hpp
  src/Channel.cpp
  src/ChannelCommand.cpp
  src/ChannelErrorMessages.cpp
  src/ChannelMode.cpp
  src/Client.cpp
  src/Command.cpp
  src/ConnexionCommand.cpp
  src/IRCError.cpp
  src/IRCSocket.cpp
  src/Server.cpp
Labels: enhancement

#64 Fix: nick
  src/IRCError.cpp
Labels: bug, enhancement

#65 Refactor close server
  header/Channel.hpp
  header/Server.hpp
  src/Bot.cpp
  src/Channel.cpp
  src/ChannelCommandJoinPart.cpp
  src/Server.cpp
Labels: enhancement

#66 Fix: 0 to NULL
  src/Server.cpp
Labels: bug
